server:
  port: 8765

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  application:
    name: app-gateway
  cloud:
    config:
      .enabled: false
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

