server:
  port: 8765

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application:  service-app-gateway

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{correlationID:-}] "
  include-application-name: false

spring:
  application:
    name: app-gateway
  cloud:
    config:
      .enabled: false
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

